(function() {
  const _0xpool = ["J3VzZSBzdHJpY3Qn","Jyc=","Jyc=","Jyc=","Jyc=","J1xuXG4n","JyNjb250ZW50LWNvbnRhaW5lciAuY29udGVudGJveCc=","Jyc=","Jyc=","J2kn","J3Jhbic=","J2V4cmFuJw==","J2gn","J3Qn","J3Yn","Jyc=","Jyc=","IlNUVl9DT05URU5UX1JFQURZIg==","ImNvbG9yOmxpbWU7Zm9udC1zaXplOjE0cHgi","J2En","Jyc=","J0NoxrDGoW5nIHNhdSc=","IkNoxrDGoW5nIHNhdSI=","IkVYVFJBQ1RfTk9XIg==","Jyc=","Jyc=","Jyc=","IkdPX05FWFQi","IltFeHRyYWN0b3JdIOKGkiBHT19ORVhUIg==","IlNUVl9QQUdFX0xPQURFRCI=","JyVjW0V4dHJhY3Rvcl0gdjQuMSByZWFkeSEn","J2NvbG9yOmN5YW47Zm9udC1zaXplOjE0cHgn"];
  const _0xcache = {};
  const _0xstr = function(i) {
    if (_0xcache[i] !== undefined) return _0xcache[i];
    const s = atob(_0xpool[i]);
    // The string still has its original quotes, so we slice them off
    const res = s.slice(1, -1);
    _0xcache[i] = res;
    return res;
  };
  // Original logic starts here
  (function() { _0xstr(0); let sent = false; const cleanText = (text) => { return (text || _0xstr(1)) .replace(/[\u200B\u200C\u200D\uFEFF]/g, _0xstr(2)) .replace(/@Bạn đang đọc bản lưu trong hệ thống/g, _0xstr(3)) .replace(/Đang tải nội dung chương\.\.\./g, _0xstr(4)) .replace(/\n{3,}/g, _0xstr(5)) .trim(); }; const doExtract = () => { const box = document.querySelector(_0xstr(6)); if (!box) return _0xstr(7); const inner = cleanText(box.innerText); let obf = _0xstr(8); box.querySelectorAll(_0xstr(9)).forEach(el => { if ((el.id && el.id.startsWith(_0xstr(10))) || el.id?.startsWith(_0xstr(11)) || el.hasAttribute(_0xstr(12)) || el.hasAttribute(_0xstr(13)) || el.hasAttribute(_0xstr(14))) { obf += el.textContent; } }); obf = cleanText(obf); return obf.length > inner.length ? obf : inner; }; const sendToBackground = (content) => { if (sent || content.length < 200) return; sent = true; const title = (document.title || _0xstr(15)).split(/\s+-\s+/)[0]?.trim() || _0xstr(16); chrome.runtime.sendMessage({ type: _0xstr(17), content, title, url: location.href, length: content.length }); console.log(`%c[Extractor] ✅ ${content.length} ký tự — ${title}`, _0xstr(18)); }; const clickNextChapter = () => { const links = document.querySelectorAll(_0xstr(19)); for (const a of links) { const text = (a.textContent || _0xstr(20)).trim(); if (text.includes(_0xstr(21))) { console.log(`[Extractor] Click _0xstr(22) → ${a.href}`); a.click(); return true; } } return false; }; const autoExtract = () => { if (sent) return; const content = doExtract(); if (content.length > 200) { sendToBackground(content); } }; const startPolling = () => { for (let i = 0; i < 15; i++) { setTimeout(autoExtract, 1500 + i * 1000); } }; startPolling(); chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => { if (msg.type === _0xstr(23)) { sent = false; const tryExtract = (n) => { if (n <= 0) { sendResponse({ content: _0xstr(24), length: 0 }); return; } const content = doExtract(); if (content.length > 200) { const title = (document.title || _0xstr(25)).split(/\s+-\s+/)[0]?.trim() || _0xstr(26); sendResponse({ content, title, length: content.length, url: location.href }); } else { setTimeout(() => tryExtract(n - 1), 1000); } }; setTimeout(() => tryExtract(12), 1500); return true; } if (msg.type === _0xstr(27)) { console.log(_0xstr(28)); const ok = clickNextChapter(); sendResponse({ ok }); return false; } }); chrome.runtime.sendMessage({ type: _0xstr(29), url: location.href }); console.log(_0xstr(30), _0xstr(31)); })();
})();